namespace: cisco
name: sdwan
version: 0.3.6
readme: README.md
authors:
  - Arkadiusz Cichon <acichon@cisco.com>
description: Ansible collection to provide full workflows for deployment, upgrades and configuration

repository: https://github.com/cisco-en-programmability/ansible-collection-sdwan
documentation: https://github.com/cisco-en-programmability/ansible-collection-sdwan/blob/main/README.md
homepage: https://github.com/cisco-en-programmability/ansible-collection-sdwan
issues: https://github.com/cisco-en-programmability/ansible-collection-sdwan/issues

license:
  - "GPL-3.0-only"

tags:
  - cisco
  - sdwan
  - catalystwan
  - networking

dependencies:
  "cisco.sdwan_deployment": ">=0.1.1"
  "cisco.catalystwan": ">=0.1.1"
  "amazon.aws": ">=6.5.0"
  "azure.azcollection": ">=1.19.0"

build_ignore: []
