collections:
- name: amazon.aws
  version: 6.5.0
- name: git@sdwan-git.cisco.com:sdwan-tools/cisco.catalystwan.git
  type: git
  version: main
- name: git@sdwan-git.cisco.com:sdwan-tools/cisco.sdwan_deployment.git
  type: git
  version: main
