collections:
  - name: amazon.aws
    version: 6.5.0
  - name: azure.azcollection
    version: 1.19.0
  - name: cisco.catalystwan
    version: 0.3.3
  - name: cisco.sdwan_deployment
    version: 0.3.4
