# --- Backup device configuration workflow --- #

# Scenario includes following operations:

# Backup device configuration (device/feature templates and policies)
# Removal all Non-Default templates
# Restore all templates from backup directory

---

- name: Backup device configuration workflow
  hosts: localhost
  gather_facts: false
  vars_files:
    - configuration_file.yml
  vars:
    manager_authentication: &manager_authentication
      url: "{{ (manager_instances | first).mgmt_public_ip }}"
      username: "{{ (manager_instances | first).admin_username }}"
      password: "{{ (manager_instances | first).admin_password }}"
  tasks:
    - name: Perform backup of all non factory default Device Templates (no filters == backup non factory default)
      cisco.catalystwan.device_templates_recovery:
        mode: backup
        backup_dir_path: ./output_backup_device_configuration
        manager_credentials:
          <<: *manager_authentication

    - name: Get all Device Templates that are not attached to any device and are Feature based
      cisco.catalystwan.device_templates_info:
        filters:
          devices_attached: 0
          factory_default: false
          config_type: template
        manager_credentials:
          <<: *manager_authentication
      register: device_templates

    - name: Delete selected Device Templates from Manager
      cisco.catalystwan.device_templates:
        state: absent
        template_name: "{{ device_template.name }}"
        manager_credentials:
          <<: *manager_authentication
      loop: "{{ device_templates.templates_info | default([], True) }}"
      loop_control:
        loop_var: device_template
      when: device_templates.templates_info | length > 0

    - name: Get all Non-Default Feature Templates available
      cisco.catalystwan.feature_templates_info:
        filters:
          factory_default: false
          devices_attached: 0
        manager_credentials:
          <<: *manager_authentication
      register: feature_templates

    - name: Delete all Non-Default Feature templates
      cisco.catalystwan.feature_templates:
        state: absent
        template_name: "{{ template.name }}"
        manager_credentials:
          <<: *manager_authentication
      loop: "{{ feature_templates.templates_info | default([], true) }}"
      loop_control:
        loop_var: template
        label: "template: {{ template.name }}"

    - name: Restore configuration from provided backup directory
      cisco.catalystwan.device_templates_recovery:
        mode: restore
        backup_dir_path: ./output_backup_device_configuration
        manager_credentials:
          <<: *manager_authentication
