# --- Templates creation and attachment - created from Feature Templates --- #

# Scenario includes following operations:

# Create Following templates for Controller devices:
# - AAA
# - System
# - VPN - VPN 0
# - VPN - VPN 512
# - VPN Interface - VPN 0
# - VPN Interface - VPN 512
# Create Device Template for Controller
# Attach Device Template for Controller


- name: Workflow for Templates creation and attachment - created from Feature Templates
  hosts: localhost
  gather_facts: false
  vars_files:
    - configuration_file.yml
  vars:
    manager_authentication: &manager_authentication
      url: "{{ (manager_instances | first).mgmt_public_ip }}"
      username: "{{ (manager_instances | first).admin_username }}"
      password: "{{ (manager_instances | first).admin_password }}"
  tasks:
    - name: Create AAA Template for Controller devices
      cisco.catalystwan.feature_templates:
        state: present
        template_name: "AAA_for_Controller"
        template_description: "AAA Template"
        device_models: vsmart
        aaa:
          auth_fallback: false
          admin_auth_order: false
          accounting: false
          usergroup:
            - name: basic
              task:
                - mode: system
                  permission:
                    - read
                - mode: interface
                  permission:
                    - read
            - name: netadmin
              task: []
            - name: operator
              task:
                - mode: system
                  permission:
                    - read
                - mode: interface
                  permission:
                    - read
                - mode: policy
                  permission:
                    - read
                - mode: routing
                  permission:
                    - read
                - mode: security
                  permission:
                    - read
          user:
            - name: "{{ template_data.admin_username }}"
              password: "{{ template_data.admin_password }}"
        manager_credentials:
          <<: *manager_authentication

    - name: Create System Template for Controller devices
      cisco.catalystwan.feature_templates:
        state: present
        template_name: "System_for_Controller"
        template_description: "System Template"
        device_specific_variables:
          site_id: "side_id_variable"
        device_models: vsmart
        system_vsmart:
          site_id: device_specific_variable
        manager_credentials:
          <<: *manager_authentication

    - name: Create VPN template for Controller devices - VPN 0
      cisco.catalystwan.feature_templates:
        state: present
        template_name: "VPN_0_for_Controller"
        template_description: "VPN_0 Template"
        device_models: vsmart
        vpn_vsmart:
          vpn_id: 0
        manager_credentials:
          <<: *manager_authentication

    - name: Create VPN template for Controller devices - VPN 512
      cisco.catalystwan.feature_templates:
        state: present
        template_name: "VPN_512_for_Controller"
        template_description: "VPN_512 Template"
        device_models: vsmart
        vpn_vsmart:
          vpn_id: 512
        manager_credentials:
          <<: *manager_authentication

    - name: Create VPN Interface template for Controller devices - VPN 0
      cisco.catalystwan.feature_templates:
        state: present
        template_name: "VPN_0_Interface_for_Controller"
        template_description: "VPN_0 Interface Template"
        device_models: vsmart
        vpn_vsmart_interface:
          if_name: eth1
          shutdown: false
          dhcp_ipv4_client: true
          dhcp: true
          dns: true
          icmp: true
          sshd: true
          netconf: true
          ntp: false
          stun: false
        manager_credentials:
          <<: *manager_authentication

    - name: Create VPN Interface template for Controller devices - VPN 512
      cisco.catalystwan.feature_templates:
        state: present
        template_name: "VPN_512_Interface_for_Controller"
        template_description: "VPN_512 Interface Template"
        device_models: vsmart
        vpn_vsmart_interface:
          if_name: eth0
          shutdown: false
          dhcp_ipv4_client: true
        manager_credentials:
          <<: *manager_authentication

    - name: Create example Device Template for Controller
      cisco.catalystwan.device_templates:
        state: present
        template_name: "Controller-test-device-template"
        template_description: "Controller-test-device-template"
        device_type: vsmart
        general_templates:
          - name: "System_for_Controller"
            subtemplates:
              - "Factory_Default_Logging_Template_V01"
          - name: "AAA_for_Controller"
          - name: "Factory_Default_Controller_OMP_Template"
          - name: "Factory_Default_Controller_Manager_Security_Template"
          - name: "VPN_0_for_Controller"
            subtemplates:
              - "VPN_0_Interface_for_Controller"
          - name: "VPN_512_for_Controller"
            subtemplates:
              - "VPN_512_Interface_for_Controller"
        manager_credentials:
          <<: *manager_authentication

    - name: Attach example Device Template to Controller
      cisco.catalystwan.device_templates:
        state: attached
        template_name: "Controller-test-device-template"
        device_type: vsmart
        hostname: "{{ template_data.controller_hostname }}"
        device_specific_vars:
          - "//system/site-id": "333"
          - "//system/host-name": "{{ template_data.controller_hostname }}"
          - "//system/system-ip": "192.168.2.1"
          - "//system/ipv6-strict-control": false
        manager_credentials:
          <<: *manager_authentication

    - name: Detach example Device Template from Controller
      cisco.catalystwan.device_templates:
        state: detached
        hostname: "{{ template_data.controller_hostname }}"
        manager_credentials:
          <<: *manager_authentication
