# --- Running config for cEdge devices workflow --- #

# Scenario includes following operations:

# Backup running config to CWD directory
# Reuse running configuration to create templates
# Attach backup templates

---

- name: Running config workflow
  hosts: localhost
  gather_facts: false
  vars_files:
    - configuration_file.yml
  vars:
    manager_authentication: &manager_authentication
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
  tasks:
    - name: Backup running-config for all c8000V devices with default backup dir (in CWD)
      cisco.catalystwan.devices_info:
        backup: true
        backup_dir_path: ./output_backup_running_config
        filters:
          personality: "vedge"
        manager_credentials:
          <<: *manager_authentication
      register: backup_info

    - name: Using backup files, create CLI templates for each Edge device
      cisco.catalystwan.cli_templates:
        state: present
        template_name: "backup-template-{{ device_item.filename }}"
        template_description: "Template for {{ device_item.hostname }} created from backup file."
        config_file: "{{ device_item.backup_path }}"
        device_model: vedge-C8000V
        manager_credentials:
          <<: *manager_authentication
      loop: "{{ backup_info.backup_paths }}"
      loop_control:
        loop_var: device_item
      when: backup_info.backup_paths | length > 0

    - name: Attach backup templates to the Edge devices
      cisco.catalystwan.device_templates:
        state: attached
        template_name: "backup-template-{{ device_item.filename }}"
        hostname: "{{ device_item.hostname }}"
        manager_credentials:
          <<: *manager_authentication
      loop: "{{ backup_info.backup_paths }}"
      loop_control:
        loop_var: device_item
      when: backup_info.backup_paths | length > 0
