# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)


# Minimal configuration file to deploy Manager, Validator, vSmart and cEdge instances

#######################################
#     Required configuration data     #
#######################################

organization_name: null


#####################################
#     General AWS configuration     #
#####################################

aws_region: us-east-1
aws_availibility_zone: us-east-1a
aws_resources_prefix: "{{ organization_name }}"

# aws_allowed_subnets is list of subnets, that are allowed to access your instances via security group in AWS
# See https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html to learn more
#
# example configuration is:
# aws_allowed_subnets:
#   - 15.15.0.0/16
#   - 10.10.0.0/16
aws_allowed_subnets: null

#######################################
#     Deployment configuration        #
#######################################

ux20_deployment: true  # NOTE remove or set to false for UX1.0 deployment

###############################
#          Controllers        #
###############################

# do not use 'admin' as password since it will cause the playbooks to fail
admin_password: null

# Manager
aws_manager_ami_id: null
aws_manager_instance_type: "c5.9xlarge"

manager_instances:
  - hostname: "{{ aws_resources_prefix }}-Manager"
    system_ip: 192.168.1.1
    site_id: 111
# NOTE uncomment for cluster deployment
#  - hostname: "{{ aws_resources_prefix }}-Manager2"
#    system_ip: 192.168.4.1
#    site_id: 112
#  - hostname: "{{ aws_resources_prefix }}-Manager3"
#    system_ip: 192.168.5.1
#    site_id: 113


# Validator
aws_validator_ami_id: null
aws_validator_instance_type: "c5.large"

validator_instances:
  - hostname: "{{ aws_resources_prefix }}-Validator"
    system_ip: 192.168.3.1
    site_id: 222


# vSmart
aws_vsmart_ami_id: null
aws_vsmart_instance_type: "c5.large"

vsmart_instances:
  - hostname: "{{ aws_resources_prefix }}-vSmart"
    system_ip: 192.168.2.1
    site_id: 333


################################
#          Edge devices        #
################################

# cedge C8000K
aws_cedge_ami_id: null
aws_cedge_instance_type: "c5.large"

# If no edge instances configured, they will be automatically created
# based on the PnP Portal information.
# See `deployment_edges_config` to inspect result


##########################################
#       Reusable deployment facts        #
##########################################

results_dir: "{{ playbook_dir }}/results"
results_path_controllers: "{{ results_dir }}/controllers.yml"
results_path_edges: "{{ results_dir }}/edges.yml"

# Required by role: cisco.catalystwan.sync_pnp_edges
deployment_edges_config: "{{ results_dir }}/edges_from_pnp_bootstrap.yml"
